---
- name: Install modern configuration
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  notify: restart sshd

- name: Deactivate short moduli
  shell:
    executable: /bin/sh
    cmd: |
      set -eu
      tmpfile=$(mktemp /tmp/moduli.XXXX)
      awk '$5 >= 3071' /etc/ssh/moduli > $tmpfile
      cp -a /etc/ssh/moduli /etc/ssh/moduli.bak
      cat $tmpfile > /etc/ssh/moduli
      rm $tmpfile
    creates: /etc/ssh/moduli.bak
  notify: restart sshd
