---
- name: Get OpenSSH Server version
  command: rpm --query --queryformat %{VERSION} openssh-server
  args:
    warn: False
  register: openssh_version
  changed_when: False

- name: Install modern configuration
  become: yes
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  notify: restart sshd

- name: Deactivate short moduli
  become: yes
  command: /bin/sh -c 'cp -a /etc/ssh/moduli /etc/ssh/moduli.bak && awk '"'"'$5 >= 3071'"'"' /etc/ssh/moduli > /etc/ssh/moduli.tmp && mv /etc/ssh/moduli.tmp /etc/ssh/moduli'
  args:
    creates: /etc/ssh/moduli.bak
  notify: restart sshd
