---
systemd_template: &systemd
  command: /sbin/init
  environment:
    container: docker
  tmpfs:
    - /run
    - /tmp
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  capabilities:
    - SYS_ADMIN

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: fedora-rawhide
    image: docker.io/fedora:rawhide
    <<: *systemd
  - name: fedora-31
    image: docker.io/fedora:31
    <<: *systemd
  - name: fedora-30
    image: docker.io/fedora:30
    <<: *systemd
  - name: centos-8
    image: docker.io/centos:8
    <<: *systemd
  - name: centos-7
    image: docker.io/centos:7
    <<: *systemd
provisioner:
  name: ansible
verifier:
  name: ansible
