---
- name: Prepare
  hosts: all
  tasks:

  - name: Install required packages
    package:
      name:
      - openssh-server
      - sudo
      state: present

  - name: Start service
    service:
      name: sshd
      state: started
